#! /bin/sh
#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.
#
#
# create a cordova/android project
# 
# USAGE
#   ./create [path package activity]
#################################################################
# Last Modified Date: 02 July 2012								#
# Author: Gihan Karunarathne									#
#################################################################

# load up the config
. ./android.config
. ./build.properties

PROJECT_PATH=$app_output_dir

PACKAGE_AS_PATH=$(echo $PACKAGE | sed 's/\./\//g')
ACTIVITY_PATH=./$PROJECT_PATH/src/$PACKAGE_AS_PATH/$ACTIVITY.java
MANIFEST_PATH=./$PROJECT_PATH/AndroidManifest.xml

# create the project
android create project --target $TARGET --path ./$PROJECT_PATH --package $PACKAGE --activity $ACTIVITY
echo "created an Android project."

# copy all the cordova scripts etc in there
cp -R ./template_android/res/* ./$PROJECT_PATH/res/
echo "copied res/"

# copy in cordova.js
mkdir ./$PROJECT_PATH/assets
mkdir ./$PROJECT_PATH/assets/www
mkdir ./$PROJECT_PATH/assets/www/js
cp ./template_android/cordova-$VERSION.js ./$PROJECT_PATH/assets/www/js
# cordova.js will be copied in mobile build

# copy in cordova.jar
cp ./template_android/cordova-$VERSION.jar ./$PROJECT_PATH/libs

# copy in res/xml
cp -R ./template_android/xml ./$PROJECT_PATH/res/

# copy in default activity
cat ./template_android/Activity.java > $ACTIVITY_PATH

# copy in AndroidMenifest.xml
cp ./template_android/AndroidManifest.xml ./$PROJECT_PATH/

# interpolate the acivity name and package
find "$ACTIVITY_PATH" | xargs grep '__ACTIVITY__' -sl | xargs -L1 sed -i -e "s/__ACTIVITY__/${ACTIVITY}/g"
find "$ACTIVITY_PATH" | xargs grep '__ID__' -sl | xargs -L1 sed -i -e "s/__ID__/${PACKAGE}/g"

find "$MANIFEST_PATH" | xargs grep '__ACTIVITY__' -sl | xargs -L1 sed -i -e "s/__ACTIVITY__/${ACTIVITY}/g"
find "$MANIFEST_PATH" | xargs grep '__PACKAGE__' -sl | xargs -L1 sed -i -e "s/__PACKAGE__/${PACKAGE}/g"
